### ISSUE TITLE
two Anthozoa taxa but only one node

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#48]
While we're correctly representing Eptesicus and Hippopotamos and three other cases where two taxa with different ranks have the same name, we missed Anthozoa, which is both a class and a subphylum. Here's a query to check for all such cases:
````
PREFIX kgo: <http://solid.boltz.cs.cmu.edu:3030/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?label ?x ?xRank ?y ?yRank WHERE {
  ?x rdfs:label|skos:prefLabel|skos:altLabel ?label.
  ?x kgo:taxonRank/rdfs:label ?xRank.
  ?y rdfs:label|skos:prefLabel|skos:altLabel ?label.
  ?y kgo:taxonRank/rdfs:label ?yRank filter (?x = ?y && ?xRank != ?yRank).
} ORDER BY ?label
````

**Comment by deyaliao** [comment]
I believe I've fixed it now. In my scraping algorithm, I also made note of which taxa names were repeats, so that in the future we'll have note of what to change before any changes are made to Data.ttl.

**Comment by touretzkyds** [comment]
Now we have two Anthozoa nodes, but the latest version of demo2d assigns both of them the taxon rank of "Class" when in the property view, whereas the higher one is actually a subphylum. I'm tagging @nhadlaw to fix this one.

**Comment by touretzkyds** [comment]
Now the taxon ranks are correct, but navigation is partly broken:

Start at Anthozoa-subphylum, switch to Full view, and click on the node to switch to property view. Use the navigation arrows to go down three levels to Alyconacea. The property view shows the parent as Octocorallia but the navigation history and navigation arrows show the parent as Anthozoa. If you then click on Octocorallia you end up at Anthozoa-genus, not Octocorallia, and both instances of Anthozoa in the navigation history are shown in pink, which should never happen.

@nhadlaw please fix this buggy code.

**Comment by nhadlaw** [comment]
The latest version of demo2d.html has fixed this issue. If there are any other issues let me know.

**Comment by touretzkyds** [comment]
Better, but still not 100% correct behavior.

1. Start with a fresh demo.
2. Type "Cnidaria" in the search box.
3. Switch to "Full" view.
4. Click on the down arrow to get to Anthozoa-subphylum. The view switches back to Concise -- it shouldn't do that. The view (Full, Moderate, or Concise) should stay the same until the user changes it.

**Comment by nhadlaw** [comment]
The reason it does this is because it's mimicking the behavior of if a user enters a taxon into the box. We said that when a user types a taxon and they hit enter, we first show them the Concise view. Since the nav button is replicating this behavior, this is why we see the Concise graph any time we switch taxons. I didn't know if we wanted to stay consistent with this functionality or adjust it for the nav buttons?

**Comment by touretzkyds** [comment]
Ah, okay. I think this was a mistake. We should not be changing the view from what the user chose. On startup we want to be in concise view, but if the user changes the view we should stick with their choice.
